# Fab Hiring Metrics Project 2018

```{r}
library(readxl)
library(forecast)
library(tidyquant)
library(timetk)
library(sweep)
library(ggplot2)
library(lubridate)
library(openxlsx)
library(scales)
library(writexl)
library(gtools)

write <- 'no'
```
# load data
```{r}
p = '/Users/jarad/Fake Folder/Fab/Projects/Fab Hiring Metrics Project 2018/CSVs/'
t = 'Fab Hiring Metrics Projects 2018 - for R.xlsx'

main <- read_excel(paste(p,t, sep = ''))
main$`year and month` <- paste(main$`year and month`,'-01',sep = '')
main$`year and month` <- as.Date(main$`year and month`)
```

# plot it
```{r}
ggplot(main, aes(x = main$`year and month`, y = main$`elapsed (seconds)`)) + 
  geom_line()
```

# convert to time series object/prep for forecasting
```{r}
d <- min(main$`year and month`)
y <- as.integer(substring(d,1,4))
m <- as.integer(substring(d,6,7))
main2 <- ts(main[,c('elapsed (seconds)')], start = c(y,m), freq = 12)
main2
```

# create model
```{r}
mod <- auto.arima(main2)
mod
```

# get and plot forecast
```{r}
fcast <- forecast(mod, h = 5, level = c(95))
autoplot(fcast) + 
  labs(x = 'year', 
       y = 'employee count',
       title = 'Actual data and forecast for the number of employees needed to test and prep') +
  scale_y_continuous(labels = function(x) round(x/3600/20/5,0))#, labels = comma)
```

# put together the final using "hours needed per day"
```{r}
final <- sw_sweep(fcast, timekit_idx = TRUE)
names(final)[names(final) == 'index'] <- 'year and month'

ls = c('year and month','key','lo.95','elapsed (seconds)','hi.95')
final <- final[, ls]

for (col in c('lo.95','elapsed (seconds)','hi.95')){
  final[,col] <- final[,col]/60/60/20
  final[,col] <- round(final[,col], 2)
}

names(final)[names(final) == 'elapsed (seconds)'] <- 'hours needed per day in a 20 day work-month'
tail(final, 10)
```

# get number of employees needed per 5 hour shift
```{r}
emp <- final
for (col in c('lo.95','hours needed per day in a 20 day work-month','hi.95')){
  # assume one person works 5 hours per day
  emp[,c(col)] <- emp[,c(col)]/5
  emp[,c(col)] <- round(emp[,c(col)],0)
}
names(emp)[names(emp) == 'hours needed per day in a 20 day work-month'] <- 'employees needed based on a 5 hour workday'
tail(emp, 10)
```

# write to excel
```{r}
if (write == 'yes'){
  workbook_ls <- list('estimated hrs needed' = final,
                    'estimated emp needed' = emp)
  workbook_title <- 'Fab Hiring Metrics 2018 Output.xlsx'
  write.xlsx(workbook_ls, file = paste(p, workbook_title, sep = ''))
}
```

```{r}
print('done')
```

